spring:
  application:
    name: chunk-file-upload

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

document:
  storage:
    base-path: storage/
    max-file-size: 10MB
    file-buffer-length: 128KB
    allowed-extensions: jpg,jpeg,png,pdf
  presigned-url:
    expiration-time: 15
    secret-key: ${PRESIGNED_URL_SECRET:your-secret-key-here}
